### PR TITLE
Introduce life-cycle-event-handler, introduce react bridge module, modify play-services dependency

### PR DESCRIPTION
**Pull request by christocracy**
- Introduce life-cycle-event-handler in order to toggle `map#setMyLocationEnabled` when app pauses / resumes.  This is important for other location-management modules which control location-services and desire to turn off location-services to conserve battery.  

- Also introduced a React bridge-module allowing the app code to execute methods upon the view instead of relying solely upon properties.  I wanted to be able to simply `addLocation(markerConfig)` instead of redrawing the entire list-of-markers each time I record a new location.  

- I've renamed the class `RNGMapsModule` to `RNGMapsViewManager`, since this class is not strictly a Module as it extends `SimpleViewManager`.  I've then claimed the name `RNGMapsModule` to implement the bridge-module.  

- Changed `play-services` dependency to import only `com.google.android.gms:play-services-maps` instead of including the entire, **immense** play-services library

### CODE REVIEW

**Comment by christocracy** [comment]
- I've also added the ability to define a custom marker [#icon](https://github.com/transistorsoft/react-native-gmaps/blob/master/android/app/src/main/java/com/rota/rngmaps/RNGMapsViewManager.java#L174), which references an image placed in the app's `app/assets` folder



Eg:
```javascript
    {
        title: location.timestamp,
        icon: "green-circle.png",  // <-- app/assets/green-circle.png
        anchor: [0.5, 0.5],  // <-- anchor location to center of marker.
        coordinates: {
          lat: location.coords.latitude,
          lng: location.coords.longitude
        }
      };
```

**Comment by christocracy** [comment]
FYI I'm the developer of the react-native module [react-native-background-geolocation](https://github.com/transistorsoft/react-native-background-geolocation).

I'm using this lib to for the map-layer in my demo-app for my background location-tracking module.  I hope you'll agree to my proposed PR as I've got a bunch of other stuff I'd like to add, including `Polyline` support.

**Comment by rreusser** [comment]
:+1:

Can't speak to the rest with 100% certainty but the [com.google.android.gms:play-services-maps](https://github.com/teamrota/react-native-gmaps/pull/9/files#diff-dc46f9f5dfe204e394fb41395ccd03cfR26) specification definitely fixed my issue. Thanks @christocracy!

**Comment by christocracy** [comment]
I've added a `Polyline` API to my branch now.  I'm still figuring out the react-native machinery, but I don't mind how this works.

I basically treat a Polyline like a database Model.

@rreusser A Polyline API is a step towards implementing your driving directions requirement.

```
var Polyline = require('react-native-gmaps/Polyline');

Polyline.create({
  color: '#0000cc',
  width: 15,
  geodesic: true,
  visible: true,
  points: [
    [51.5, -0.1], [40.7, -74.0]
  ]
}, function(polyline) {  // <-- success callback
  polyline.addPoint(45.5192919, -73.6169509, function(success) {
    console.log("- addPoint success");
  });
  
  polyline.setState({
    color: '#ff0000',
    width: 20
  }, function(success) {
    console.log('- setState success');
  });

  // Remove it
  polyline.remove();

});
```

**Comment by kirkness** [comment]
This is awesome; good work. Apologies for the delay in getting this merged!

**Pull request merged**
